
import React, { useState } from 'react';
// import PixelArt from './PixelArt'; // Remove import

const ImageWithFallback: React.FC<{ src: string; alt: string; fallback: React.ReactNode; className?: string }> = ({ src, alt, fallback, className }) => {
    const [error, setError] = useState(false);
    if (error) return <div className="flex items-center justify-center w-full h-full">{fallback}</div>;
    return <img src={src} alt={alt} className={className} onError={() => setError(true)} />;
};

export const ItemIcon: React.FC<{ id: string; className?: string }> = ({ id, className }) => {
    // Reverting to emoji-only to prevent API quota exhaustion (429 errors)
    // as per user request "作物アイコンを無くしてください" (Please remove crop icons).
    // The PixelArt component generates too many requests for the large number of items.
    const emoji = getEmoji(id);
    const isImage = emoji.endsWith('.png') || emoji.endsWith('.jpg') || emoji.endsWith('.jpeg') || emoji.endsWith('.gif');

    return (
        <div className={`${className || 'w-10 h-10'} flex items-center justify-center text-2xl bg-white border-2 border-[#4a3b32] shadow-sm overflow-hidden`}>
            {isImage ? (
                <ImageWithFallback src={emoji} alt={id} className="w-full h-full object-cover" fallback="📦" />
            ) : (
                emoji
            )}
        </div>
    );
};

export const EMOJI_MAP: Record<string, string> = {
    // Facilities
    field: 'IMG7487.png',
    ship: '🚢',
    ranch: '🏠',
    center_pivot: '⛲',
    large_fishing_boat: '⛴️',
    feedlot: '🏭',

    // Crops - Veggies
    spinach: 'IMG_7487.png',
    komatsuna: '🥬',
    chingensai: '🥬',
    mizuna: '🌿',
    shungiku: '🌿',
    mini_tomato: '🍅',
    eggplant: '🍆',
    green_pepper: '🫑',
    paprika: '🫑',
    cucumber: '🥒',
    zucchini: '🥒',
    okra: '🎋',
    bitter_melon: '🥒',
    pumpkin: '🎃',
    corn: '🌽',
    potato: '🥔',
    sweet_potato: '🍠',
    daikon_radish: '🥢',
    carrot: '🥕',
    onion: '🧅',
    garlic: '🧄',
    ginger: '🫚',
    green_onion: '🎋',
    wakegi: '🎋',
    rakkyo: '🧄',
    shallot: '🧅',
    pea: '🫛',
    broad_bean: '🫛',
    green_bean: '🫛',
    snap_pea: '🫛',
    edamame: '🫛',
    shiso: '🌿',
    mitsuba: '🌿',
    basil: '🌿',
    parsley: '🌿',
    dill: '🌿',
    fennel: '🌿',
    rosemary: '🌿',
    thyme: '🌿',
    sage: '🌿',
    coriander: '🌿',
    artichoke: '🥬',
    radish: '🔴',
    arugula: '🥗',
    watercress: '🥗',
    ice_plant: '❄️',
    molokheiya: '🌿',
    chorogi: '🐛',
    wasabi: '🟢',
    truffle: '🍄',
    mushroom: '🍄',
    shiitake: '🍄',
    eringi: '🍄',
    maitake: '🍄',
    shimeji: '🍄',
    nameko: '🍄',
    kikurage: '🍄',
    enoki: '🍄',
    sprout: '🌱',
    kaiware_daikon: '🌱',
    beet: '🍠',
    swiss_chard: '🥬',
    hakusai: '🥬',
    kohlrabi: '🥬',
    bamboo_shoot: '🎍',
    kuwai: '🥔',
    yacon: '🥔',
    cassava: '🥔',
    sesame: '⚫',
    sunflower_seed: '🌻',
    kale: '🥬',
    romanesco: '🥦',
    chestnut_pumpkin: '🎃',
    western_pumpkin: '🎃',
    luffa: '🥒',
    fudansou: '🥬',
    jalapeno_pepper: '🌶️',
    habanero_pepper: '🌶️',
    cayenne_pepper: '🌶️',
    radish_red_white: '🔴',
    salad_greens: '🥗',
    microgreen: '🌱',
    suizenjina: '🌿',

    // Fruits
    apple: '🍎',
    tomato: '🍅',
    grape: '🍇',
    orange: '🍊',
    banana: '🍌',
    mango: '🥭',
    peach: '🍑',
    cherry: '🍒',
    pineapple: '🍍',
    strawberry: '🍓',
    melon: '🍈',
    watermelon: '🍉',
    lemon: '🍋',
    lime: '🟢',
    kiwi: '🥝',
    blueberry: '🫐',
    raspberry: '🍓',
    blackberry: '🫐',
    apricot: '🍑',
    prune: '🟣',
    persimmon: '🟠',
    pear: '🍐',
    pomegranate: '🔴',
    grapefruit: '🍊',
    dragon_fruit: '🐲',
    passion_fruit: '🟣',
    mangosteen: '🟣',
    coconut: '🥥',
    cacao: '🍫',
    feijoa: '🟢',
    mulberry: '🟣',
    nectarine: '🍑',
    quince: '🍐',
    pawpaw: '🟡',
    finger_lime: '🟢',
    star_fruit: '⭐',
    jackfruit: '🍈',
    durian: '🍈',
    tamarillo: '🔴',
    acerola: '🍒',
    gumi: '🔴',
    rose_hip: '🌹',
    white_sapote: '🟢',
    cherimoya: '🟢',
    rambutan: '🔴',
    sapodilla: '🟤',
    jaboticaba: '🟣',
    carambola: '⭐',
    camellia_fruit: '🔴',
    guava: '🟢',
    currant: '🔴',
    
    // Fish
    horse_mackerel: '🐟',
    mackerel: '🐟',
    tuna: '🐟',
    sea_bream: '🐠',
    flounder: '🐠',
    bonito: '🐟',
    yellowtail: '🐟',
    amberjack: '🐟',
    kelp_bass: '🐟',
    blackthroat_seaperch: '🐟',
    abalone: '🐚',
    scallop: '🐚',
    crab: '🦀',
    shrimp: '🦐',
    squid: '🦑',
    octopus: '🐙',
    smelt: '🐟',
    pufferfish: '🐡',
    conger_eel: '🐍',
    anglerfish: '🐟',
    rockfish: '🐟',
    alfonsin: '🐟',
    okhotsk_atka_mackerel: '🐟',
    sea_bass: '🐟',
    greenling: '🐟',
    mahi_mahi: '🐟',
    mullet: '🐟',
    catfish: '🐟',
    cornetfish: '🐟',
    devil_stinger: '🐟',
    lionfish: '🐠',
    hairtail: '🐟',
    flathead: '🐟',
    filefish: '🐟',
    pleuronectidae: '🐟',
    salmon: '🐟',
    mantis_shrimp: '🦐',
    sea_squirt: '🔴',
    flying_fish: '🐟',
    blenny: '🐟',
    sea_robin: '🐟',
    black_sea_bream: '🐟',
    surfperch: '🐟',
    loach: '🐟',
    moray_eel: '🐍',
    cherry_salmon: '🐟',
    goatfish: '🐟',
    wrasse: '🐟',
    red_spotted_grouper: '🐟',
    halibut: '🐟',
    ito: '🐟',
    yamame: '🐟',
    oikawa: '🐟',
    barracuda: '🐟',
    gnomefish: '🐟',
    red_stingray: '🐟',
    silver_whiting: '🐟',
    plotosus: '🐟',
    cod: '🐟',
    sand_borer: '🐟',
    red_sea_bream: '🐟',
    spanish_mackerel: '🐟',
    flat_seabass: '🐟',
    ugui: '🐟',
    marlin: '🐟',
    marbled_rockfish: '🐟',
    goby: '🐟',
    giant_pacific_octopus: '🐙',
    pacific_bluefin_tuna: '🐟',
    guineafowl_puffer: '🐡',
    anthias: '🐟',
    kawamutsu: '🐟',
    hime_dai: '🐟',
    grouper: '🐟',
    sea_snake: '🐍',
    japanese_barracuda: '🐟',
    walleye_pollock: '🐟',
    jewel_bass: '🐟',
    red_grouper: '🐟',
    japanese_common_squid: '🦑',
    red_queen_crab: '🦀',
    snow_crab: '🦀',
    sea_chub: '🐟',
    black_rockfish: '🐟',
    barracuda_mackerel: '🐟',
    armored_seabream: '🐟',
    northern_red_ray: '🐟',
    halfbeak: '🐟',
    porcupinefish: '🐡',
    drum_fish: '🐟',
    murasoi: '🐟',
    takanohadai: '🐟',
    john_dory: '🐟',
    large_drum_fish: '🐟',
    yellow_seabream: '🐟',
    medai: '🐟',
    bumphead_parrotfish: '🐟',
    threadfin_bream: '🐟',
    saury: '🐟',
    eel: '🐍',

    // Meat
    beef_sirloin: '🥩',
    beef_fillet: '🥩',
    beef_belly: '🥩',
    beef_thigh: '🥩',
    beef_rump: '🥩',
    beef_neck: '🥩',
    beef_shank: '🥩',
    beef_tail: '🥩',
    pork_loin: '🍖',
    pork_belly: '🍖',
    pork_shoulder_loin: '🍖',
    pork_fillet: '🍖',
    pork_thigh: '🍖',
    pork_spare_rib: '🍖',
    pork_hormone: '🍖',
    pork_ear: '👂',
    pork_foot: '🦶',
    pork_heart: '❤️',
    chicken_wing_meat: '🍗',
    chicken_wing_tip: '🍗',
    chicken_thigh: '🍗',
    chicken_breast: '🍗',
    chicken_tenderloin: '🍗',
    chicken_tail: '🍗',
    chicken_liver: '🍗',
    chicken_gizzard: '🍗',
    chicken_heart: '❤️',
    chicken_cartilage: '🍗',
    horse_loin: '🐎',
    horse_fillet: '🐎',
    horse_thigh: '🐎',
    horse_belly: '🐎',
    horse_neck: '🐎',
    horse_sinew: '🐎',
    horse_tongue: '👅',
    horse_liver: '🐎',
    horse_heart: '❤️',
    horse_diaphragm: '🐎',
    wild_boar_loin: '🐗',
    wild_boar_belly: '🐗',
    wild_boar_thigh: '🐗',
    wild_boar_shoulder_loin: '🐗',
    wild_boar_shank: '🐗',
    wild_boar_neck: '🐗',
    wild_boar_fillet: '🐗',
    wild_boar_heart: '❤️',
    wild_boar_liver: '🐗',
    wild_boar_tongue: '👅',
    deer_loin: '🦌',
    deer_thigh: '🦌',
    deer_belly: '🦌',
    deer_fillet: '🦌',
    deer_shank: '🦌',
    deer_neck: '🦌',
    deer_tongue: '👅',
    deer_heart: '❤️',
    deer_liver: '🦌',
    deer_rib_loin: '🦌',
    beef_loin: '🥩',
    
    // Products
    apple_pie: '🥧',
    tomato_soup: '🥣',
    spinach_and_komatsuna_green_dance: '🥗',
    chingensai_and_mizuna_spring_bowl: '🥗',
    shungiku_and_mitsuba_japanese_risotto: '🥘',
    mini_tomato_and_paprika_sun_marinate: '🥗',
    eggplant_and_zucchini_purple_green_confit: '🍆',
    green_pepper_and_okra_summer_grill: '🍢',
    bitter_melon_and_shishito_pepper_cool_stir_fry: '🍳',
    pumpkin_and_sweet_potato_hearty_stew: '🍲',
    potato_and_taro_earth_potage: '🥣',
    yam_and_lotus_root_sticky_salad: '🥗',
    daikon_radish_and_burdock_flavorful_stew: '🍲',
    celery_and_asparagus_crunchy_salad: '🥗',
    onion_and_garlic_sweet_sauce: '🥫',
    ginger_and_green_onion_seasoning_soup: '🥣',
    wakegi_and_rakkyo_small_accent: '🥢',
    shallot_and_pea_french_flavor: '🇫🇷',
    broad_bean_and_green_bean_bean_feast: '🫛',
    snap_pea_and_corn_sweet_stir_fry: '🌽',
    edamame_and_shiso_japanese_tempura: '🍤',
    mitsuba_and_basil_japanese_western_harmony: '🌿',
    parsley_and_dill_herb_paradise: '🌿',
    fennel_and_rosemary_mediterranean_grill: '🍖',
    thyme_and_sage_herb_garden_chicken: '🍗',
    coriander_and_arugula_ethnic_salad: '🥗',
    artichoke_and_radish_western_appetizer: '🍽️',
    watercress_and_ice_plant_waterside_salad: '🥗',
    molokheiya_and_chorogi_sticky_bowl: '🍚',
    wasabi_and_ginger_refreshing_salad: '🥗',
    truffle_and_mushroom_aromatic_pasta: '🍝',
    shiitake_and_eringi_forest_saute: '🍳',
    maitake_and_shimeji_autumn_mushroom_hot_pot: '🍲',
    nameko_and_kikurage_smooth_soup: '🥣',
    enoki_and_sprout_crunchy_salad: '🥗',
    kaiware_daikon_and_sprout_refreshing_salad: '🥗',
    beet_and_swiss_chard_colorful_roast: '🍠',
    hakusai_and_kohlrabi_light_pickle_salad: '🥗',
    bamboo_shoot_and_kuwai_spring_simmer: '🍲',
    yacon_and_cassava_exotic_salad: '🥗',
    sesame_and_sunflower_seed_nutty_dressing: '🥗',
    kale_and_romanesco_green_power_smoothie: '🥤',
    chestnut_pumpkin_and_western_pumpkin_sweet_potage: '🥣',
    luffa_and_fudansou_rare_stir_fry: '🍳',
    jalapeno_pepper_and_habanero_pepper_fire_sauce: '🌶️',
    cayenne_pepper_and_radish_red_white_spicy_marinate: '🌶️',
    salad_greens_and_microgreen_delicate_salad: '🥗',
    suizenjina_and_spinach_green_gratin: '🥘',
    apple_and_tomato_sweet_sour_compote: '🍎',
    carrot_and_grape_orange_risotto: '🥘',
    orange_and_banana_sun_fruit_salad: '🥗',
    mango_and_peach_tropical_dessert: '🍨',
    cherry_and_pineapple_red_yellow_tart: '🥧',
    strawberry_and_melon_sweet_jewel_box: '🎁',
    watermelon_and_lemon_refreshing_drink: '🍹',
    lime_and_kiwi_sour_sherbet: '🍧',
    blueberry_and_raspberry_berry_parfait: '🍨',
    blackberry_and_apricot_deep_jam: '🍯',
    prune_and_persimmon_japanese_compote: '🥣',
    pear_and_pomegranate_moist_salad: '🥗',
    grapefruit_and_dragon_fruit_vitamin_cocktail: '🍸',
    passion_fruit_and_mangosteen_tropical_dessert: '🍮',
    coconut_and_cacao_rich_mousse: '🍫',
    feijoa_and_mulberry_rare_jam: '🍯',
    nectarine_and_quince_baked_fruit: '🥧',
    pawpaw_and_finger_lime_exotic_salad: '🥗',
    star_fruit_and_jackfruit_mystery_dessert: '🍮',
    durian_and_tamarillo_strong_marinate: '🥗',
    acerola_and_gumi_vitamin_bomb: '💊',
    rose_hip_and_white_sapote_herb_tea_jelly: '🍮',
    cherimoya_and_rambutan_creamy_dessert: '🍨',
    sapodilla_and_jaboticaba_south_american_fruit_plate: '🍽️',
    carambola_and_camellia_fruit_garnish: '🍽️',
    guava_and_currant_tropical_sauce: '🥣',
    horse_mackerel_and_mackerel_japanese_marinate: '🐟',
    tuna_and_sea_bream_luxurious_bowl: '🍚',
    flounder_and_bonito_skillful_sear: '🔥',
    yellowtail_and_amberjack_cold_selection: '❄️',
    kelp_bass_and_blackthroat_seaperch_premium_simmer: '🍲',
    abalone_and_scallop_shell_steam: '🐚',
    crab_and_shrimp_seafood_paella: '🥘',
    squid_and_octopus_mediterranean_grill: '🐙',
    smelt_and_pufferfish_rare_fry: '🍤',
    conger_eel_and_anglerfish_deep_hot_pot: '🍲',
    rockfish_and_alfonsin_salt_grill_assortment: '🐟',
    okhotsk_atka_mackerel_and_sea_bass_dried_plate: '🍽️',
    greenling_and_mahi_mahi_white_fry: '🍤',
    mullet_and_catfish_fry_two_kinds: '🍤',
    cornetfish_and_devil_stinger_aspic: '🍮',
    lionfish_and_hairtail_showy_grill: '🔥',
    flathead_and_filefish_liver_salad: '🥗',
    pleuronectidae_and_salmon_butter_saute: '🧈',
    mantis_shrimp_and_sea_squirt_sea_pasta: '🍝',
    flying_fish_and_blenny_light_marinate: '🥗',
    sea_robin_and_black_sea_bream_tide_soup: '🥣',
    surfperch_and_loach_country_simmer: '🍲',
    moray_eel_and_cherry_salmon_intimidating_grill: '🔥',
    goatfish_and_wrasse_tropical_salad: '🥗',
    red_spotted_grouper_and_halibut_steamed_dish: '♨️',
    ito_and_yamame_river_fish_fry: '🍤',
    oikawa_and_barracuda_karaage: '🍗',
    beef_loin_and_pork_belly_meaty_stew: '🍲',
    grilled_saury: '🐟',
    eel_bowl: '🍱',
    
    // Minerals
    diamond: '💎',
    gold: '🥇',
    platinum: '🥈',
    iron: '🪨',
    copper: '🥉',
    silver: '🥈',
    aluminum: '🪙',
    tin: '🥫',
    sulfur: '🌋',
    brass: '🎺',
    
    // Weapons
    musket: '🔫',
    charlemagnes_sword: '⚔️',
};

export const getEmoji = (id: string, fallback: string = '📦') => {
    if (EMOJI_MAP[id]) return EMOJI_MAP[id];
    if (id.includes('beef') || id.includes('pork') || id.includes('chicken') || id.includes('meat') || id.includes('horse') || id.includes('boar') || id.includes('deer')) return '🥩';
    if (id.includes('fish') || id.includes('mackerel') || id.includes('tuna') || id.includes('bream') || id.includes('salmon') || id.includes('bass')) return '🐟';
    if (id.includes('crab')) return '🦀';
    if (id.includes('shrimp')) return '🦐';
    if (id.includes('squid')) return '🦑';
    if (id.includes('shell') || id.includes('clam')) return '🐚';
    if (id.includes('fruit')) return '🍎';
    if (id.includes('vegetable')) return '🥬';
    return fallback;
}

const IconWrapper: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <div className="w-8 h-8 flex items-center justify-center text-2xl bg-white border-2 border-[#4a3b32] shadow-sm overflow-hidden">
        {children}
    </div>
);

export const MoneyIcon = () => <IconWrapper>💰</IconWrapper>;
export const FarmIcon = () => <IconWrapper><ImageWithFallback src="IMG7487.png" alt="Farm" className="w-full h-full object-cover" fallback="🌾" /></IconWrapper>;
export const WarehouseIcon = () => <IconWrapper>🛖</IconWrapper>;
export const MarketIcon = () => <IconWrapper>🏪</IconWrapper>;
export const LabIcon = () => <IconWrapper>🧪</IconWrapper>;
export const RuinsIcon = () => <IconWrapper>🏛️</IconWrapper>;
export const CompanyIcon = () => <IconWrapper>🏢</IconWrapper>;
export const TenantIcon = () => <IconWrapper>🏘️</IconWrapper>;
export const MineIcon = () => <IconWrapper>⛏️</IconWrapper>;
export const SmithyIcon = () => <IconWrapper>🔨</IconWrapper>;
export const CountryIcon = () => <IconWrapper>🌍</IconWrapper>;
export const SystemIcon = () => <IconWrapper>⚙️</IconWrapper>;
export const NationalismIcon = () => <IconWrapper>🚩</IconWrapper>;
export const RecruiterIcon = () => <IconWrapper>🤝</IconWrapper>;
export const NBAIcon = () => <IconWrapper>🏀</IconWrapper>;

// Utility Icons
export const CountryTimeIcon = () => <span>⏱️</span>;
export const CropTimeIcon = () => <span>🌾⏱️</span>;
export const SellPriceIcon = () => <span>💰</span>;
export const FragmentChanceIcon = () => <span>🧩</span>;
export const RuinTimeIcon = () => <span>🏛️⏱️</span>;
export const CitizenIcon = () => <span>👥</span>;
export const StarIcon = () => <span>★</span>;
export const CrownIcon = () => <span>👑</span>;
export const ShieldIcon = () => <span>🛡️</span>;
export const TerrainIcon = () => <span>⛰️</span>;
export const EntertainmentIcon = () => <span>🎭</span>;
export const MiniMapIcon = () => <span>🗺️</span>;
export const TrophyIcon = () => <span>🏆</span>;
export const TournamentIcon = () => <span>⚔️</span>;
